#Rabbit
rabbit:
  host: ${RABBIT_HOST:localhost}
  username: ${RABBIT_USERNAME:guest}
  password: ${RABBIT_PASSWORD:guest}
  queue:
    receive: ${RABBIT_QUEUE_RECEIVE:test-queue}
    transmit: ${RABBIT_QUEUE_TRANSMIT:test-queue}

#Telegram
telegram:
  bot:
    name: ${TELEGRAM_BOT_NAME:test-bot}
    token: ${TELEGRAM_BOT_TOKEN}

#Kubernetes probes
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
